services:

  h61:
    container_name: h61
    hostname: h61
    image: alpine
    networks:
      lan60:
        ipv4_address: 192.168.60.61
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  h62:
    container_name: h62
    hostname: h62
    image: alpine
    networks:
      lan60:
        ipv4_address: 192.168.60.62
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  h71:
    container_name: h71
    hostname: h71
    image: alpine
    networks:
      lan70:
        ipv4_address: 192.168.70.71
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  h72:
    container_name: h72
    hostname: h72
    image: alpine
    networks:
      lan70:
        ipv4_address: 192.168.70.72
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  h91:
    container_name: h91
    hostname: h91
    image: alpine
    networks:
      lan90:
        ipv4_address: 192.168.90.91
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  h92:
    container_name: h92
    hostname: h92
    image: alpine
    networks:
      lan90:
        ipv4_address: 192.168.90.92
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  h93:
    container_name: h93
    hostname: h93
    image: alpine
    networks:
      lan90:
        ipv4_address: 192.168.90.93
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  R1:
    container_name: R1
    hostname: R1
    image: giditre/frr
    networks:
      net12:
        ipv4_address: 10.0.12.10
      net13:
        ipv4_address: 10.0.13.10
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  R2:
    container_name: R2
    hostname: R2
    image: giditre/frr
    networks:
      net12:
        ipv4_address: 10.0.12.20
      net23:
        ipv4_address: 10.0.23.20
      net24:
        ipv4_address: 10.0.24.20
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  R3:
    container_name: R3
    hostname: R3
    image: giditre/frr
    networks:
      net13:
        ipv4_address: 10.0.13.30
      net23:
        ipv4_address: 10.0.23.30
      # net38:
      #   ipv4_address: 10.0.38.30
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  R4:
    container_name: R4
    hostname: R4
    image: giditre/frr
    networks:
      net24:
        ipv4_address: 10.0.24.40
      net45:
        ipv4_address: 10.0.45.40
      net46:
        ipv4_address: 10.0.46.40
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  R5:
    container_name: R5
    hostname: R5
    image: giditre/frr
    networks:
      net45:
        ipv4_address: 10.0.45.50
      net57:
        ipv4_address: 10.0.57.50
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  R6:
    container_name: R6
    hostname: R6
    image: giditre/frr
    networks:
      net46:
        ipv4_address: 10.0.46.60
      lan60:
        ipv4_address: 192.168.60.60
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  R7:
    container_name: R7
    hostname: R7
    image: giditre/frr
    networks:
      net57:
        ipv4_address: 10.0.57.70
      lan70:
        ipv4_address: 192.168.70.70
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  R8:
    container_name: R8
    hostname: R8
    image: giditre/frr
    networks:
      # net38:
      #   ipv4_address: 10.0.38.80
      net89:
        ipv4_address: 10.0.89.80
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  R9:
    container_name: R9
    hostname: R9
    image: giditre/frr
    networks:
      net89:
        ipv4_address: 10.0.89.90
      lan90:
        ipv4_address: 192.168.90.90
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    stdin_open: true
    tty: true

  ryu:
    container_name: ryu
    hostname: ryu
    image: giditre/ryu
    stdin_open: true
    tty: true
    ports:
      - "6633:6633"
      - "8080:8080"

networks:

  lan60:
    name: lan60
    ipam:
      config:
        - subnet: 192.168.60.0/24
    driver_opts:
      com.docker.network.bridge.name: br-lan60

  lan70:
    name: lan70
    ipam:
      config:
        - subnet: 192.168.70.0/24
    driver_opts:
      com.docker.network.bridge.name: br-lan70

  lan90:
    name: lan90
    ipam:
      config:
        - subnet: 192.168.90.0/24
    driver_opts:
      com.docker.network.bridge.name: br-lan90

  net12:
    name: net12
    ipam:
      config:
        - subnet: 10.0.12.0/24
    driver_opts:
      com.docker.network.bridge.name: br-net12

  net13:
    name: net13
    ipam:
      config:
        - subnet: 10.0.13.0/24
    driver_opts:
      com.docker.network.bridge.name: br-net13

  net23:
    name: net23
    ipam:
      config:
        - subnet: 10.0.23.0/24
    driver_opts:
      com.docker.network.bridge.name: br-net23

  net24:
    name: net24
    ipam:
      config:
        - subnet: 10.0.24.0/24
    driver_opts:
      com.docker.network.bridge.name: br-net24

  net45:
    name: net45
    ipam:
      config:
        - subnet: 10.0.45.0/24
    driver_opts:
      com.docker.network.bridge.name: br-net45

  net46:
    name: net46
    ipam:
      config:
        - subnet: 10.0.46.0/24
    driver_opts:
      com.docker.network.bridge.name: br-net46

  net57:
    name: net57
    ipam:
      config:
        - subnet: 10.0.57.0/24
    driver_opts:
      com.docker.network.bridge.name: br-net57

  # net38:
  #   name: net38
  #   ipam:
  #     config:
  #       - subnet: 10.0.38.0/24
  #   driver_opts:
  #     com.docker.network.bridge.name: br-net38

  net89:
    name: net89
    ipam:
      config:
        - subnet: 10.0.89.0/24
    driver_opts:
      com.docker.network.bridge.name: br-net89
